version: 2.1

jobs:
  build:
    docker:
      - image: maven:latest
    working_directory: /pi-device-sdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - pi-device-sdk-{{ checksum "pom.xml" }}
      - run:
          name: package
          command: mvn package

workflows:
  build-workflow:
    jobs:
      - build
