version: 2.1

jobs:
  build:
    docker:
      - image: maven:latest
    working_directory: ~/pi-device-sdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - pi-device-sdk-{{ checksum "pom.xml" }}
      - run:
          name: package
          command: mvn package
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

workflows:
  build-workflow:
    jobs:
      - build